version: '3.8'

volumes:
  mysql_db-volumes:
    driver: local

networks:
  php_advanced:
    driver: bridge

services:
  php:
    build:
      context: .docker/php

    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    networks:
      - php_advanced

  db:
    image: "mysql:8"
    restart: always
    ports:
      - "36061:3606"
    environment:
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - "mysql_db-volumes:/var/lib/mysql"
    networks:
      - php_advanced

  adminer:
    image: "adminer"
    ports:
      - "8081:8080"
    networks:
      - php_advanced